### ISSUE TITLE
WWI and the Department only displays XML

### ISSUE THREAD

**Issue by machalou** [HistoryAtState/other-publications#2]
@joewiz @tomfaith The WWI page of the website is throwing an error and only showing the raw XML of the page. Just noticed it this morning.

**Comment by joewiz** [comment]
Looking into it...

**Comment by joewiz** [comment]
Looks like there was a bad commit: https://github.com/HistoryAtState/hsg-shell/commit/464d28668fe85dfaf641f09c94e1a6ac8162628f. @tomfaith My guess is that you previously uploaded a fixed/normal version of this file to hsg, but you encountered a problem ("conflicts") when committing the file to GitHub (as the link here will show). Since we updated the servers last Thurs/Fri, we redeployed the entire site from the up-to-date contents of GitHub. Will you be able to repair the file, uploading it to hsg and committing it to GitHub?

**Comment by joewiz** [comment]
@tomfaith I've retrieved the file from a backup of the server. I'll commit/upload this and paste in the link for you to review the diff and confirm it's ok.

**Comment by joewiz** [comment]
https://github.com/HistoryAtState/hsg-shell/commit/c9b2c80f2791141024ad58e3b2f443ddd58a1724

... now live on hsg.

**Comment by machalou** [comment]
Thanks!

**Comment by joewiz** [comment]
@machalou Thanks so much for spotting it!
